name: Validate Secret

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  check-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate Secret
        run: |
          if [[ "${{ secrets.MY_SECRET }}" == "KEY" ]]; then
            echo "✅ Secreto es válido"
          else
            echo "❌ Secreto es inválido"
            exit 1
          fi

      - name: Print feature flag
        run: echo "Feature flag is tiene el valor de ${{ vars.FEATUREFLAG }}"
